---

- hosts: all

  roles:
    - role: weareinteractive.sudo
      become: yes

    - role: geerlingguy.docker
      become: yes

    - pre_kubernetes

    - role: geerlingguy.kubernetes
      become: yes

  pre_tasks:
    - name: Update apt cache.
      become: yes
      apt: update_cache=yes cache_valid_time=600

- hosts: masters

  roles:
    - kube_config
 
