---

- name: Disable swap
  include_tasks: disable_swap.yml
  when: disable_swap | bool

- name: Rename host
  include_tasks: rename_host.yml
  when: host_name is defined

- name: Add NFS common
  include_tasks: nfs_common.yml

- name: Prepare Docker
  include_tasks: prepare_docker.yml
