---

- name: Change host name
  become: yes
  hostname:
    name: "{{ host_name }}"

- name: Replace rock64 with the host name
  become: yes
  replace:
    path: /etc/hosts
    regexp: '^(127\.0\.[0|1]\.1).*'
    replace: '\1 localhost {{ host_name }}'

